[options]

cleanOutput = True
runMadGraph = True
runPythia = True
runDelphes = False
runAnalysis = False
runMadSpin = False
ncpu = 1 
ncore = 7 

[AuxPars]
#Test to probe the MadAnalysis5 recasting
y1Masses = $loop{numpy.array([2000])} 
xdMasses = $loop{numpy.array([1])} 
#Validation 
#y1Masses = $loop{numpy.array([])} 
#xdMasses = $loop{numpy.array([])}
gq_values = $loop{numpy.array([1/4])} 
qx_values = $loop{numpy.array([1.0])} 
ne = 70000

[MadGraphPars]

#MG5 Cards:
proccard = Cards/Cards_Spin1/proc_card_mg5_LO.dat
paramcard = Cards/Cards_Spin1/param_card.dat
runcard = Cards/run_card_match.dat
delphescard = Cards/delphes_card_atlas_exot_2016_27.tcl
pythia8card = Cards/pythia8_card_match.dat 
processFolder = ../DMSimp_Events_Simulated_MG5/DMSimp_DVM_pp_xxj_LO
#../../remote_directory/ATLAS-EXOT-2018-06/DMSimp_Events_Simulated_MG5/DMSimp_spin1_xxjets_LO 

[MadGraphSet]#

nevents = ${AuxPars:ne} # Number of events to generate
MY1 = ${AuxPars:y1Masses} # Mass of the Z' boson
MXd= ${AuxPars:xdMasses} # Dark matter mass
MXc = 0.0
MXr = 0.0
gVXd = ${AuxPars:qx_values} # Vector coupling of the Z' to Dark matter
gAXd = 0.0
gVXc = 0.0 
gVd11 = ${AuxPars:gq_values} # Vector coupling of the Z' to d
gVd22 = ${AuxPars:gq_values} # Vector coupling of the Z' to s
gVd33 = ${AuxPars:gq_values} # Vector coupling of the Z' to b
gVu11 = ${AuxPars:gq_values} # Vector coupling of the Z' to u
gVu22 = ${AuxPars:gq_values} # Vector coupling of the Z' to c
gVu33 = ${AuxPars:gq_values} # Vector coupling of the Z' to t
gAd11 = 0.0 # Axial coupling of the Z' to quarks b
gAd22 = 0.0 # Axial coupling of the Z' to quarks s
gAd33 = 0.0 # Axial coupling of the Z' to quarks b
gAu11 = 0.0 # Axial coupling of the Z' to quarks u
gAu22 = 0.0 # Axial coupling of the Z' to quarks c
gAu33 = 0.0 # Axial coupling of the Z' to quarks t
WY1 = auto # Width of the Z' boson  
xqcut = "%1.0f" %(${MY1}/15.0))
r#un_tag = "mzp_%1.1f_gq_%1.2f_mx_%1.1f_gx_%1.1f" %(${MY1},${gVd11},${MXd},${gVXd}) # Tag for the run
run_tag = "mzp_%1.1f_mx_%1.1f_nevents_%1.0f" %(${MY1},${MXd},${nevents}) # Tag for the run