[options]
cleanOutput = True
runMadGraph = True
runPythia = False
runDelphes = False
runAnalysis = False
runMadSpin = False
ncpu = 1 
ncore = 7 

[AuxPars]
y0Masses = $loop{[10,  10,  50,  50,  50,  50, 100, 100, 100, 100, 100,  95, 200, 200, 200, 200, 201, 295, 350, 350, 350, 350, 350, 350, 350, 350, 500, 500, 500, 500, 500, 500, 500, 500, 500]}
xdMasses = $loop{[50, 150,   1,  10,  20,  50,   1,  10,  20,  30,  40,  50,   1, 20,  50,  75,  95, 150,   1,  25,  50,  75, 100, 125, 150, 170, 1,  25,  50,  75, 100, 125, 150, 175, 200]}
gq_values = 1.0
qx_values = 1.0
ne = 2000


[MadGraphPars]
#MG5 Cards:
proccard = Cards/Cards_Spin0/proc_card_mg5_ppYxxLO.dat
paramcard = Cards/Cards_Spin0/param_card.dat
runcard = Cards/run_card.dat
delphescard = Cards/delphes_card_atlas_exot_2016_27.tcl
pythia8card = Cards/pythia8_card_default.dat
processFolder = ../DMSimp_Events_Simulated_MG5/DMSimp_DMP_pp_xx_LO
#../../remote_directory/ATLAS-EXOT-2018-06/DMSimp_Events_Simulated_MG5/DMSimp_spin0_xxjets 


[MadGraphSet]#
nevents = ${AuxPars:ne}  # Number of events to generate
MY0 = ${AuxPars:y0Masses} # Mass of the Z' boson
MXd= ${AuxPars:xdMasses} # Dark matter mass
MXc = 0.0
MXr = 0.0
gPXd = ${AuxPars:qx_values} # Vector coupling of the Z' to Dark matter
gSXd = 0.0
gPXc = 0.0 
gPd11 = ${AuxPars:gq_values} # Vector coupling of the Z' to d
gPd22 = ${AuxPars:gq_values} # Vector coupling of the Z' to s
gPd33 = ${AuxPars:gq_values} # Vector coupling of the Z' to b
gPu11 = ${AuxPars:gq_values} # Vector coupling of the Z' to u
gPu22 = ${AuxPars:gq_values} # Vector coupling of the Z' to c
gPu33 = ${AuxPars:gq_values} # Vector coupling of the Z' to t
gSd11 = 0.0 # Axial coupling of the Z' to quarks b
gSd22 = 0.0 # Axial coupling of the Z' to quarks s
gSd33 = 0.0 # Axial coupling of the Z' to quarks b
gSu11 = 0.0 # Axial coupling of the Z' to quarks u
gSu22 = 0.0 # Axial coupling of the Z' to quarks c
gSu33 = 0.0 # Axial coupling of the Z' to quarks t
WY0 = auto # Width of the Z' boson  
run_tag = "mMed_%1.1f_mx_%1.1f" %(${MY0},${MXd}) # Tag for the run
