[options]

cleanOutput = True
runMadGraph = True
runPythia = False
runDelphes = False
runAnalysis = False
runMadSpin = False
ncpu = 1 
ncore = 7

[AuxPars]

y1Masses = $loop{numpy.arange(100.0, 2500.0, 100)}
#$loop{[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400]} 
#$loop{[1000, 500, 600]}
xdMasses = $loop{[0., 50., 100.,  200., 300., 400., 500., 600., 700., 800., 900., 1000.]} 
#xdMasses = ${y1Masses}/2
#$loop{[100, 200, 50]}
gq_values = 1/4
qx_values = 1.0
pdf = 263600
ne = 3000 #11040


[MadGraphPars]

#MG5 Cards:
proccard = Cards/Cards_Spin1/proc_card_mg5_OnShell.dat
paramcard = Cards/Cards_Spin1/param_card.dat
runcard = Cards/Cards_Spin1/run_card.dat
delphescard = Cards/delphes_card_atlas_exot_2016_27.tcl
pythia8card = Cards/Cards_Spin1/pythia8_card.dat
processFolder = ../../Insync/DMSimp_DMA_SMS

[MadGraphSet]#

ebeam1 = 6500
ebeam2 = 6500
pdlabel = lhapdf 
lhaid = ${AuxPars:pdf}  #pdf number 
dynamical_scale_choice = 3 # Utiliza la suma de las masas transversas/2 para calcular la escala de renormalización.
scalefact = 1 # scale factor for event-by-event scales? 0.5 para la mitad de la escala,
nevents = ${AuxPars:ne} # Number of events to generate


MY1 = ${AuxPars:y1Masses} # Mass of the Z' boson
MXd= ${AuxPars:xdMasses} # Dark matter mass
gAXd = ${AuxPars:qx_values} # Vector coupling of the Z' to Dark matter
gVXd = 0.0
gVXc = 0.0 
gVd11 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to d
gVd22 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to s
gVd33 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to b
gVu11 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to u
gVu22 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to c
gVu33 = 0.0 #${AuxPars:gq_values} # Vector coupling of the Z' to t
gAd11 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks b
gAd22 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks s
gAd33 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks b
gAu11 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks u
gAu22 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks c
gAu33 = ${AuxPars:gq_values} #0.0 # Axial coupling of the Z' to quarks t
gvh = 0
WY1 = auto # Width of the Z' boson 
run_tag = "mzp_%1.0f_mx_%1.0f" %(${MY1},${MXd}) # Tag for the run