[options]

cleanOutput = False
runMadGraph = True
runPythia = True
runDelphes = False
runAnalysis = False
runMadSpin = False
ncpu = 1 
ncore = 7

[AuxPars]

y0Masses = 350
xdMasses = 1
y0Masses = $loop{[10, 10, 10, 50, 50, 50, 50, 100, 100, 100, 100, 100, 100, 200, 200, 200, 200, 200, 300, 350, 350, 350, 350, 350, 350, 350, 350, 500, 500, 500, 500, 500, 500, 500, 500, 500]}
xdMasses = $loop{[ 5, 50, 150, 1, 10, 20, 50, 1, 10, 20, 30, 40, 50, 1, 20, 50, 75, 95, 150, 1, 25, 50, 75, 100, 125, 150, 170, 1, 25, 50, 75, 100, 125, 150, 175, 200]}
gq_values = 1.0
qx_values = 1.0
pdf = 263600
ne = 250000


[MadGraphPars]
#MG5 Cards:
proccard = Cards/Cards_Spin0/proc_card_mg5_LO.dat
#proccard = Cards/Cards_Spin0/proc_card_mg5_LO_match.dat
paramcard = Cards/Cards_Spin0/param_card.dat
runcard = Cards/Cards_Spin0/run_card.dat
#runcard = Cards/run_card_match.dat
delphescard = Cards/delphes_card_atlas_exot_2016_27.tcl
pythia8card = Cards/Cards_Spin0/pythia8_card.dat
#pythia8card = Cards/pythia8_card_match.dat
processFolder = ../../Insync/DMSimp_Pseudoescalar_pp_xxj_eff



[MadGraphSet]#

ebeam1 = 6500
ebeam2 = 6500
pdlabel = lhapdf 
lhaid = ${AuxPars:pdf}  #pdf number 
dynamical_scale_choice = 3 
scalefact = 1 # scale factor for event-by-event scales? 1 
nevents = ${AuxPars:ne}  # Number of events to generate
ptj = 150

MY0 = ${AuxPars:y0Masses} # Mass of the Phi boson
MXd= ${AuxPars:xdMasses} # Dark matter mass
gPXd = ${AuxPars:qx_values} # Vector coupling of the Phi to Dark matter
gSXd = 0.0
gPXc = 0.0 
gPd11 = ${AuxPars:gq_values} # Vector coupling of the Phi to d
gPd22 = ${AuxPars:gq_values} # Vector coupling of the Phi to s
gPd33 = ${AuxPars:gq_values} # Vector coupling of the Phi to b
gPu11 = ${AuxPars:gq_values} # Vector coupling of the Phi to u
gPu22 = ${AuxPars:gq_values} # Vector coupling of the Phi to c
gPu33 = ${AuxPars:gq_values} # Vector coupling of the Phi to t
gSd11 = 0.0 # Axial coupling of the Phi to quarks b
gSd22 = 0.0 # Axial coupling of the Phi to quarks s
gSd33 = 0.0 # Axial coupling of the Phi to quarks b
gSu11 = 0.0 # Axial coupling of the Phi to quarks u
gSu22 = 0.0 # Axial coupling of the Phi to quarks c
gSu33 = 0.0 # Axial coupling of the Phi to quarks t
gsb = 0 
gsh1 = 0 
WY0 = auto # Width of the Phi boson 
#xqcut = 80 #"%1.0f" %(max(30.,${MY0}/1000.0))
run_tag = "mMed_%1.0f_mDM_%1.0f" %(${MY0},${MXd}) # Tag for the run
